### ISSUE TITLE
PG::InsufficientPrivilege: ERROR:  must be superuser to COPY to or from a file

### ISSUE THREAD

**Issue by jaykilleen** [diogob/postgres-copy#23]
I am working through your readme.md to see if this is a good solution for me. From the rails console I am attempting 
`Customer.copy_to '/tmp/customers.csv'` 
but getting
`PG::InsufficientPrivilege: ERROR:  must be superuser to COPY to or from a file`

Is this an issue I can have a workaround for or am I just showing my inexperience?

Appreciate your help. Looks like this might be a really useful Gem that others in the community have directed me to.

**Comment by diogob** [comment]
This is a PostgreSQL limitation. To be able to import directly from and to files you need a database superuser.
You can work around this using something like this:
```ruby
File.open('/tmp/users.csv', 'w') do |f|
  User.copy_to do |line|
    f.write line
  end
end
```
