### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by sangamgupta85** [diogob/postgres-copy#24]
Hi there

I am using postgres-copy gem to export User Account based data in CSV i.e; I want to export all the data of a particular user as his data backup. But as per the documentation, I can export only a single table's data.

Once exported, I would like to import the data exported for the particular user from same CSV to populate all the tables from which this data is exported previously.

Is something that is possible with this gem?

Thanks

**Comment by diogob** [comment]
You could export all related data using their respective models, use a scope to select data or create a model for a database view that brings all necessary data.
