### ISSUE TITLE
allow copy_from with no headers

### ISSUE THREAD

**Issue by edatrix** [diogob/postgres-copy#27]
I didn't mess around with this, so maybe you can map this in some way, but it would be nice if you can import with no headers.

**Comment by jackturnbull** [comment]
You can pass options to [`copy_from`](https://github.com/diogob/postgres-copy/blob/master/lib/postgres-copy/acts_as_copy_target.rb#L45). A `header` of `false` will skip headers.

For example:
```ruby
  Customer.copy_from 'file.csv', header: false, columns: [
    :name,
    :age,
    :date_of_birth
  ]

```
