### ISSUE TITLE
`acts_as_copy_target` not defined in Rails 3, but works great in Rails 4

### ISSUE THREAD

**Issue by brightbytes-dude** [diogob/postgres-copy#30]
My Rails 4 app is using version 0.9.2 perfectly, no issues whatsoever.

However, I just added this to my Rails 3 app (specifying version 0.6), and it crashes like so upon class loading:

```
undefined local variable or method `acts_as_copy_target' for #<Class:0x007fae10b7f2f8> (NameError)`
```

Any suggestions would be appreciated.

**Comment by brightbytes-dude** [comment]
Hmm, looks like that `acts_as_copy_target` isn't defined in the gem source in version 0.6 ... and, per your docs, the methods are all prefixed by `pg_`.  I'll remove `acts_as_copy_target` and try invoking them directly.

**Comment by diogob** [comment]
yeah, invoking then directly should work in earlier versions

**Comment by brightbytes-dude** [comment]
Yup, it does.  Sorry for the noise.  And, thanks for the very cool plugin!!
