### ISSUE TITLE
Comma inside a column causes error

### ISSUE THREAD

**Issue by scaryguy** [diogob/postgres-copy#35]
When I'm trying to `copy_from` a CSV, I'm getting an error when it's this row's turn during iteration:

```
310114,"07UT","small_airport","ATK/Thiokol Airport",41.7166667,-112.4472222,4480,"NA","US","US-UT","Howell","no","07UT",,"07UT",,,"UT23, Air Force Plant 78 Airfield"
```

The error is:
```
PG::BadCopyFileFormat: ERROR:  extra data after last expected column
CONTEXT:  COPY airports, line 3063: "310114,"07UT","small_airport","ATK/Thiokol Airport",41.7166667,-112.4472222,4480,"NA","US","US-UT","..."
```

Seems like the comma which exists at the last column confuses the gem.

**Comment by diogob** [comment]
Hi, I've added a test case for this in the commit https://github.com/diogob/postgres-copy/commit/4eef053c62c8e32d983a081095cd680e040cf60c

The tests are still green so I'm closing the issue for now, feel free to reopen or send a pull request with another test case.
