### ISSUE TITLE
Feature proposal: copy_to_enumerator

### ISSUE THREAD

**Issue by DanielHeath** [diogob/postgres-copy#42]
Currently there's a CSV responder for those using inherited_resources.

I'd like to avoid that dependency, so I've just rolled the code into my project, but I think `render_to_enumerator` would be a sensible addition alongside (e.g.) `render_to_string`.

Would a PR be welcome?

**Comment by diogob** [comment]
It surely would. I'd love to actually drop the whole responder thing from this gem, it is currently try to do too much.
But a render to enumerator seems much more aligned with the gem purpose and offers a much cleaner interface.

**Comment by diogob** [comment]
@DanielHeath thanks for the PR. I'll release a new minor version including this.
