### ISSUE TITLE
Possible to ignore created_at and updated_at?

### ISSUE THREAD

**Issue by planetaska** [diogob/postgres-copy#68]
When I tried to use copy_from, I got this error:

`Error: ERROR: null value in column "created_at" of relation "items" violates not-null constraint`

Is it possible to ignore constraints on these auto generated columns? I think not wanting to import these values is a common scenario? I tried using `columns`, but didn't work.

**Comment by diogob** [comment]
The easiest way around this is to either set default values in the database:
```sql
ALTER TABLE items ALTER created_at SET DEFAULT now();
ALTER TABLE items ALTER updated_at SET DEFAULT now();
```

**Comment by GuillaumeOcculy** [comment]
## 💡 Why this happens
When we create a new table in Rails, **`t.timestamps`** is automatically added.  
This generates two columns: **`created_at`** and **`updated_at`**.

In a normal ActiveRecord workflow, Rails **automatically sets these timestamps** via callbacks (`before_create`, `before_update`).

However, when using **Postgres COPY or bulk inserts**, ActiveRecord callbacks are bypassed, meaning **the timestamps are not set automatically**.

---

## ✅ Solution
To ensure timestamps are populated even when **ActiveRecord is not involved**, configure PostgreSQL to handle them at the database level.

### **For a new table**
Set default values at the schema level so PostgreSQL assigns timestamps automatically:

```ruby
add_timestamps :table_name, default: -> { 'CURRENT_TIMESTAMP' }, null: false
```

### **For an existing table**
If the table already exists, update the default value:

```ruby
change_column_default :table_name, :created_at, -> { 'CURRENT_TIMESTAMP' }
change_column_default :table_name, :updated_at, -> { 'CURRENT_TIMESTAMP' }
```

With this setup, **PostgreSQL, not ActiveRecord**, will manage the timestamps, making bulk inserts and COPY operations reliable without additional callbacks.
