### ISSUE TITLE
Rdoc/Rake versions vulnerable

### ISSUE THREAD

**Issue by atharnoor2** [diogob/postgres-copy#70]
Hi,

There are 2 Vulnerabilities discovered here:

https://github.com/advisories/GHSA-ggxm-pgc9-g7fp
https://security.snyk.io/vuln/SNYK-RUBY-RAKE-552000

These requires rdoc version to be updated to 6.3.1 whereas rake version to be updated to 12.3.3 in order to resolve these `High severity` vulnerabilities.

I was hoping if it would be possible to bump the versions of these gems in this rubygem ?

**Comment by diogob** [comment]
released in 1.7.1
